[translate.iso_country_lang.ell]
ell = "Greek, Modern (1453–)"
el = "Greek, Modern (1453–)"

[translate.parts_of_speech.ell]
parts_of_speech = "Part of Speech"
Noun = "Noun"
Verb = "Verb"
Adjective = "Adjective"
Adverb = "Adverb"
Pronoun = "Pronoun"
Particle = "Particle"
Auxiliary = "Auxiliary"
Conjunction = "Conjunction"
Interjection = "Interjection"
Preposition = "Preposition"
Determiner = "Determiner"
Subject = "Subject"
Object = "Object"
