[translate.iso_country_lang.isl]
isl = "Icelandic"
is = "Icelandic"

[translate.parts_of_speech.isl]
parts_of_speech = "Part of Speech"
Noun = "Noun"
Verb = "Verb"
Adjective = "Adjective"
Adverb = "Adverb"
Pronoun = "Pronoun"
Particle = "Particle"
Auxiliary = "Auxiliary"
Conjunction = "Conjunction"
Interjection = "Interjection"
Preposition = "Preposition"
Determiner = "Determiner"
Subject = "Subject"
Object = "Object"
