[translate.iso_country_lang.isl]
isl = "Icelandic"
is = "Icelandic"

[translate.parts_of_speech.isl]
parts_of_speech = "Part of Speech"
Noun = "Noun"
Verb = "Verb"
Adjective = "Adjective"
Adverb = "Adverb"
Pronoun = "Pronoun"
Particle = "Particle"
Auxiliary = "Auxiliary"
Conjunction = "Conjunction"
Interjection = "Interjection"
Preposition = "Preposition"
Determiner = "Determiner"
Subject = "Subject"
Object = "Object"

[translate.report_labels.isl]
report_title = "Þýðingarskýrsla"
generated_at = "Búið til"
totals = "Samtals"
total = "Samtals"
text = "Texti"
attachment = "Viðhengi"
language_pairs = "Tungumálapör"
content_types = "Efnisgerðir"
models = "Líkön"
daily_volume = "Daglegt magn"
translated_histories = "Þýðingarsaga"
tags = "Merki"
clusters = "Klasa"
keywords = "Lykilorð"
history_date = "Dagsetning"
history_type = "Tegund"
history_formality = "Formleiki"
history_source_lang = "Uppruni"
history_target_lang = "Markmið"
history_source_text = "Upprunatexti"
history_target_text = "Þýddur texti"
history_tags = "Merki"
unknown = "Óþekkt"
auto = "Sjálfvirkt"
type_text = "Texti"
type_audio = "Hljóð"
type_image = "Mynd"
type_video = "Myndband"
type_document = "Skjal"
type_other = "Annað"
