[translate.iso_country_lang.jpn]
af = "アフリカーンス語"
afr = "アフリカーンス語"
am = "アムハラ語"
amh = "アムハラ語"
ar = "アラビア語"
ara = "アラビア語"
ben = "ベンガル語"
bg = "ブルガリア語"
bn = "ベンガル語"
bul = "ブルガリア語"
ca = "カタロニア語"
cat = "カタロニア語"
ces = "チェコ語"
cs = "チェコ語"
cy = "ウェールズ語"
cym = "ウェールズ語"
da = "デンマーク語"
dan = "デンマーク語"
de = "ドイツ語"
deu = "ドイツ語"
el = "ギリシャ語"
ell = "ギリシャ語"
en = "英語"
eng = "英語"
es = "スペイン語"
eu = "バスク語"
eus = "バスク語"
fi = "フィンランド語"
fin = "フィンランド語"
fr = "フランス語"
fra = "フランス語"
ga = "アイルランド語"
gl = "ガリシア語"
gle = "アイルランド語"
glg = "ガリシア語"
gu = "グジャラート語"
guj = "グジャラート語"
he = "ヘブライ語"
heb = "ヘブライ語"
hi = "ヒンディー語"
hin = "ヒンディー語"
hr = "クロアチア語"
hrv = "クロアチア語"
hu = "ハンガリー語"
hun = "ハンガリー語"
id = "インドネシア語"
ind = "インドネシア語"
is = "アイスランド語"
isl = "アイスランド語"
it = "イタリア語"
ita = "イタリア語"
ja = "日本語"
jpn = "日本語"
kan = "カンナダ語"
kn = "カンナダ語"
ko = "韓国語"
kor = "韓国語"
mal = "マラヤーラム語"
mar = "マラーティー語"
ml = "マラヤーラム語"
mr = "マラーティー語"
nl = "オランダ語"
nld = "オランダ語"
no = "ノルウェー語"
nor = "ノルウェー語"
pa = "パンジャブ語"
pan = "パンジャブ語"
pl = "ポーランド語"
pol = "ポーランド語"
por = "ポルトガル語"
pt = "ポルトガル語"
ro = "ルーマニア語"
ron = "ルーマニア語"
ru = "ロシア語"
rus = "ロシア語"
sk = "スロバキア語"
sl = "スロベニア語"
slk = "スロバキア語"
slv = "スロベニア語"
spa = "スペイン語"
sr = "セルビア語"
srp = "セルビア語"
sv = "スウェーデン語"
swe = "スウェーデン語"
ta = "タミル語"
tam = "タミル語"
te = "テルグ語"
tel = "テルグ語"
th = "タイ語"
tha = "タイ語"
tr = "トルコ語"
tur = "トルコ語"
uk = "ウクライナ語"
ukr = "ウクライナ語"
vi = "ベトナム語"
vie = "ベトナム語"
yo = "ヨルバ語"
yor = "ヨルバ語"
zh = "中国語"
zho = "中国語"

[translate.parts_of_speech.jpn]
parts_of_speech = "品詞"
Noun = "名詞"
Verb = "動詞"
Adjective = "形容詞"
Adverb = "副詞"
Pronoun = "代名詞"
Particle = "助詞"
Auxiliary = "助動詞"
Conjunction = "接続詞"
Interjection = "間投詞"
Preposition = "前置詞"
Determiner = "限定詞"
Subject = "主語"
Object = "目的語"
