[translate.iso_country_lang.spa]
spa = "Spanish, Castilian"
es = "Spanish, Castilian"

[translate.parts_of_speech.spa]
parts_of_speech = "Part of Speech"
Noun = "Noun"
Verb = "Verb"
Adjective = "Adjective"
Adverb = "Adverb"
Pronoun = "Pronoun"
Particle = "Particle"
Auxiliary = "Auxiliary"
Conjunction = "Conjunction"
Interjection = "Interjection"
Preposition = "Preposition"
Determiner = "Determiner"
Subject = "Subject"
Object = "Object"
