[translate.iso_country_lang.swe]
swe = "Swedish"
sv = "Swedish"

[translate.parts_of_speech.swe]
parts_of_speech = "Part of Speech"
Noun = "Noun"
Verb = "Verb"
Adjective = "Adjective"
Adverb = "Adverb"
Pronoun = "Pronoun"
Particle = "Particle"
Auxiliary = "Auxiliary"
Conjunction = "Conjunction"
Interjection = "Interjection"
Preposition = "Preposition"
Determiner = "Determiner"
Subject = "Subject"
Object = "Object"
